package demo.firstDrools;

import org.testdrools.entity.Order;

// 规则一
rule under100
    when
        $order:Order(originalPrice < 100)
    then
        $order.setRealPrice($order.getOriginalPrice());
        System.out.println("匹配规则一：所购总价100元以下没有优惠");
 end

 // 规则二 所购图书总价在100到200元的优惠20元
// rule "计算优惠100到200的优惠20"
rule between100and200
    when
        $order:Order(originalPrice >=100 && originalPrice < 200)
    then
        $order.setRealPrice($order.getOriginalPrice() -20);
        System.out.println("匹配规则二：所购总价100元以下优惠20");
 end

 //规则三：所购图书总价在200到300元的优惠50元
// rule "书总价在200到300元的优惠50元"
rule between200and300
    when
        $order:Order(originalPrice >= 200 && originalPrice < 300)
    then
        $order.setRealPrice($order.getOriginalPrice() - 50);
        System.out.println("匹配规则三：所购总价100元以下优惠50");
 end

 //规则四：所购图书总价在300元以上的优惠100元
//  rule "书总价在300元以上的优惠100元"
rule marethan300
     when
         $order:Order(originalPrice >= 300)
     then
         $order.setRealPrice($order.getOriginalPrice() - 100);
         System.out.println("匹配规则四：所购总价100元以下优惠100");
  end

