package rules;
dialect  "mvel"

import org.testdrools.entity.Student;

rule "规则等于10岁1"
    salience 10
    when
        // 可以指定优先级控制执行顺序，默认相同的匹配规则是按照顺序进行执行
        $student:Student(age == 10)
    then
        // retract 用于删除工作内存中的Fact对象，导致重新进行下一次的匹配
        retract($student)
        System.out.println("匹配得到年龄等于10岁的规则1");
end

rule "规则等于10岁"
    when
        $student:Student(age == 10)
    then
        Student s = new Student();
        s.setAge(15);
        // 将新创建的对象放入工作内存中，并存入Fact对象中，导致相关规则重新进行下一次的匹配
        insert(s)
        System.out.println("匹配得到年龄等于10岁的规则");
end
rule "规则小于10岁"
    when
        $student:Student(age < 10)
    then
        $student.setAge(15);
        update($student);
        System.out.println("匹配得到规则小于10岁的规则 ");
end

rule "规则大于10岁小于20岁"
    when
        $student:Student(age > 10 && age < 20)
    then
        System.out.println("匹配到年龄大于10岁小于20岁的规则");
end

// 内置属性
rule "规则年龄大于20岁"
    no-loop true
    when
       $student:Student(age > 20)
    then
        $student.setAge(30);
        // 会导致死循环
        update($student)
        System.out.println("匹配到年龄大于20岁");
end
